blank_issues_enabled: false
# https://github.com/spatie/package-skeleton-php/tree/main/.github/ISSUE_TEMPLATE
contact_links:
  - name: Ask a question
    url: https://github.com/guanguans/php-cs-fixer-custom-fixers/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/guanguans/php-cs-fixer-custom-fixers/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/guanguans/php-cs-fixer-custom-fixers/security/policy
    about: Learn how to notify us for sensitive bugs
